language: python

python:
  - "2.7"

install:
    - travis_retry pip install coveralls
    - travis_retry python setup.py install

script:
    - travis_retry python setup.py test
    - coverage run --source=seth setup.py test
    - coverage report -m

after_script:
  coveralls --verbose